# Generated by Django 4.2.7 on 2025-09-20 07:35

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('master_data', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='StockMovement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('movement_type', models.CharField(choices=[('purchase', 'Purchase'), ('sale', 'Sale'), ('adjustment', 'Adjustment'), ('opening', 'Opening Stock')], max_length=20)),
                ('quantity', models.DecimalField(decimal_places=2, max_digits=10)),
                ('unit_price', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0)])),
                ('total_value', models.DecimalField(decimal_places=2, max_digits=15, validators=[django.core.validators.MinValueValidator(0)])),
                ('reference_document', models.CharField(blank=True, max_length=100, null=True)),
                ('movement_date', models.DateField()),
                ('notes', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stock_movements', to='master_data.product')),
            ],
            options={
                'db_table': 'stock_movements',
                'ordering': ['-movement_date', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='StockBalance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('opening_quantity', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('purchased_quantity', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('sold_quantity', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('adjusted_quantity', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('current_quantity', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('average_cost', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('stock_value', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('product', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='stock_balance', to='master_data.product')),
            ],
            options={
                'db_table': 'stock_balances',
            },
        ),
    ]
