# Generated by Django 4.2.7 on 2025-09-20 17:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('master_data', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='gst_number',
            field=models.CharField(blank=True, help_text='GST Number (e.g., 22AAAAA0000A1Z5)', max_length=15, null=True),
        ),
    ]
