# Generated by Django 4.2.7 on 2025-09-20 17:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customerinvoice',
            name='notes',
        ),
        migrations.RemoveField(
            model_name='customerinvoice',
            name='payment_terms',
        ),
        migrations.RemoveField(
            model_name='payment',
            name='notes',
        ),
        migrations.RemoveField(
            model_name='purchaseorder',
            name='notes',
        ),
        migrations.RemoveField(
            model_name='purchaseorder',
            name='payment_terms',
        ),
        migrations.RemoveField(
            model_name='salesorder',
            name='notes',
        ),
        migrations.RemoveField(
            model_name='salesorder',
            name='payment_terms',
        ),
        migrations.RemoveField(
            model_name='vendorbill',
            name='notes',
        ),
        migrations.RemoveField(
            model_name='vendorbill',
            name='payment_terms',
        ),
    ]
